name: Python Auto Tagging
description: Automatically generate new tags when version file changes
author: Sam Morgan & Jorrick Sleijster & ArabCoders

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: Github Token
    required: true
  path:
    description: Path to version file
    required: true
  regex:
    description: Regular expression to match the version
    required: true
  prefix:
    description: Prefix to add to the version tag
    required: false
  suffix:
    description: Suffix to add to the version tag
    required: false
  repo_name:
    description: Repository name If not provided, the repository name will be extracted from the github context.
    required: false

outputs:
  version:
    description: The version defined in the version file

runs:
  using: docker
  image: Dockerfile
